name: tag push
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 获取信息
      id: get_info
      run: |
        echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
        echo "repository_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
    - name: 拉取代码
      uses: actions/checkout@v4.1.6
    - name: 安装java8
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: 构建
      run: |
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging
    - name: 收集构建文件
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ steps.get_info.outputs.repository_name }}-Release-${{ steps.get_info.outputs.VERSION }}
        path: staging 
    - name: 发布新版本
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: ${{ steps.get_info.outputs.VERSION }}
        name: ${{ steps.get_info.outputs.VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: ./docs/changelogs/${{ steps.get_info.outputs.VERSION }}.md
        artifacts: ./staging/*.*
    # 这个暂时没有用
    # - name: 发布至minebbs
    #   uses: HuoHuas001/Minebbs-Auto-Release@v1.0.6
    #   with: 
    #     resources: '1'
    #     token: ${{ secrets.MINEBBSKEY }}
    #     title: ${{ steps.get_info.outputs.VERSION }}
    #     new_version: ${{ steps.get_info.outputs.VERSION }}
    #     description_file: ./docs/changelogs/${{ steps.get_info.outputs.VERSION }}.md
    #     file_url: 'https://github.com/${{ github.repository }}/releases/latest'